puppetclient01:
  image: docker.io/vtorhonen/puppetclient
  hostname: puppetclient01
  container_name: puppetclient01
  links:
    - puppetmaster
  dns_search:
    - .

puppetclient02:
  image: docker.io/vtorhonen/puppetclient
  hostname: puppetclient02
  container_name: puppetclient02
  links:
    - puppetmaster
  dns_search:
    - .

puppetclient03:
  image: docker.io/vtorhonen/puppetclient
  hostname: puppetclient03
  container_name: puppetclient03
  links:
    - puppetmaster
  dns_search:
    - .

puppetmaster:
  image: docker.io/vtorhonen/puppetmaster
  hostname: puppetmaster
  container_name: puppetmaster
  volumes:
    - ./master/manifests:/opt/puppet/conf/manifests
    - ./master/modules:/opt/puppet/conf/modules
    - ./master/hiera:/opt/puppet/conf/hiera
  expose:
    - "8140"
  dns_search:
    - .
